repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-executables-have-shebangs
  - id: detect-aws-credentials
    args: ["--allow-missing-credentials"] # Allow hook to pass when no credentials are detected
# black
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3
# flake8: pinned version required since flake8 doesn't have 'stable' or other generic tag in their repo
- repo: https://github.com/PyCQA/flake8 #https://gitlab.com/pycqa/flake8
  rev: 6.1.0 #3.7.5
  hooks:
  - id: flake8
    args: ["--config=.flake8"]
# terraform
#- repo: https://github.com/antonbabenko/pre-commit-terraform
#  rev: v1.81.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
#  hooks:
#    - id: terraform_fmt
#    - id: terraform_docs